CREATE TABLE equipment(
	Eno INT PRIMARY KEY ,
	Ename CHAR(20) NOT NULL,
	Ecount INT DEFAULT 0
)
ENGINE=InnoDB DEFAULT CHARSET=UTF8 COLLATE=UTF8_GENERAL_CI;
ALTER TABLE equipment ADD UNIQUE (Ename)