CREATE TABLE e_lend(
	Lendno CHAR(50) PRIMARY KEY,
	Lenddate DATETIME NOT NULL ,
	Eno INT NOT NULL,
	Lcount INT DEFAULT 0,
	Lendname CHAR(20) NOT NULL ,
	Lendphone CHAR(20) NOT NULL,
	Returndate DATE NOT NULL,
	username VARCHAR(50) NOT NULL,
	FOREIGN KEY (Eno) REFERENCES equipment(Eno),
	FOREIGN KEY (username) REFERENCES users(username)
)
ENGINE=InnoDB DEFAULT CHARSET=UTF8 COLLATE=UTF8_GENERAL_CI;