CREATE TABLE e_repair(
	Repairno CHAR(50) PRIMARY KEY,
	Repairdate DATETIME NOT NULL,
	Eno INT NOT NULL,
	Rcount INT DEFAULT 0,
	Rreason CHAR(100) NOT NULL ,
	username VARCHAR(50) NOT NULL,
	FOREIGN KEY (Eno) REFERENCES equipment(Eno),
	FOREIGN KEY (username) REFERENCES users(username)
)
ENGINE=InnoDB DEFAULT CHARSET=UTF8 COLLATE=UTF8_GENERAL_CI;