CREATE TABLE e_store(
	Listno CHAR(50) NOT NULL PRIMARY KEY ,
	Eno INT NOT NULL,
	username VARCHAR(50) NOT NULL,
	Ecount INT(2) DEFAULT '1',
	Buydate DATETIME NOT NULL,
	BuyPrice INT(11) NOT NULL,
	SaleName CHAR(50) NOT NULL,
	SalePhone CHAR(50) NOT NULL,
	Estatus CHAR(50) DEFAULT '在库',
	FOREIGN KEY (Eno) REFERENCES equipment(Eno),
	FOREIGN KEY (username) REFERENCES users(username)
)
ENGINE=InnoDB DEFAULT CHARSET=UTF8 COLLATE=UTF8_GENERAL_CI;